import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { FloatingNav } from "@/app/components/ui/floating-nav-bar";
import { cn } from "@/lib/utils";
import { Home } from "lucide-react";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans"
})

export const metadata: Metadata = {
  title: "Jeffrey's Portfolio",
  description: "Generated by create next app",
};

const navItems = [
  {
    name: "Home",
    link: "/",
    icon: <Home className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
       )}
      >
        <FloatingNav navItems={navItems}/>
        {children}
       
      </body>
    </html>
  );
}
